### ISSUE TITLE
el-menu折叠状态下，popper位置错误

### ISSUE THREAD

**Issue by knightshy** [YunYouJun/YunYouJun#19]
### Describe the bug

大佬请问这个问题现在怎么解决  https://github.com/element-plus/element-plus/issues/8573

### Reproduction

https://codesandbox.io/s/element-plus-spa-forked-okkx4f?file=/src/App.vue

### System Info

```Shell
Vue Version: 3.2.37
Element Plus Version: 2.2.5
Browser / OS: Chrome/102.0.0.0
Build Tool: Vite
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
![image](https://github.com/YunYouJun/YunYouJun/assets/25154432/a43724df-77f9-48f1-8181-971edb2ab0ae)

我尝试了新版，它似乎已经被修复。
请尝试升级依赖。

**Comment by knightshy** [comment]
@YunYouJun 谢谢大佬

**Comment by dickbinge** [comment]
目前2.77 版本还有这个问题，请问是怎么修复的呢
