### ISSUE TITLE
关于小空调

### ISSUE THREAD

**Issue by Chiaspcn** [YunYouJun/YunYouJun#3]
你好啊云游君。
我是一个小白哈哈，我在这个上面看到了你的源码，奈何我无能，并不能看懂哈哈。
我有个私心，我想既然开源了，那我应该可以架到我的服务器上吧。
但是我只会用宝塔页面直接搭载文件，但是似乎不行，哈哈。
因为我对于ui有一点想更改的地方哈哈，直接引用iframe有很大的局面性，感觉不太美观。
其实我并不知道你会不会允许我这么做，当然如果可以，希望你可以教教我怎么架到服务器哈哈，谢谢啦！ 
已加QQ群，还没有通过。

**Comment by YunYouJun** [comment]
代码开源，且允许自定义，但需保留原作者署名。
您需要自行了解前端构建的基础知识，我也没有精力一一教导群里所有提问的同学。
